micronaut:
  application:
    name: backend

  server:
    cors:
      enabled: true

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    intercept-url-map:
      - pattern: /**
        http-method: GET
        access:
          - isAnonymous()
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
              base64: true
              jws-algorithm: HS256