datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'com.valychbreak.calculator'
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: true

micronaut:
  application:
    name: backend

  server:
    port: 8080
    cors:
      enabled: true

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

  security:
    enabled: true
    endpoints:
      login:
        enabled: true
        path: /api/login
      oauth:
        enabled: true
    intercept-url-map:
      - pattern: /**
        http-method: GET
        access:
          - isAnonymous()
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
              base64: true
              jws-algorithm: HS256