
name: Frontend tests with NodeJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing using Node
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Installing modules
        run: npm install
      - name: Run tests
        run: ./node_modules/react-scripts/bin/react-scripts.js test --watchAll